services:
  postgres:
    image: postgres:latest
    container_name: schedulebuilder_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: schedulebuilder
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend: